protected/modules/usr/controllers/DefaultController.php
<?php

Yii::import('usr.controllers.UsrController');

/**
 * The default controller providing all basic actions.
 * @author Jan Was <jwas@nets.com.pl>
 */
class DefaultController extends UsrController
{
	/**
	 * @inheritdoc
	 */
	public function getId()
	{
		// use constant id to allow mapping fake controller names to this one, @see UsrModule::$controllerMap
		return 'default';
	}

	/**
	 * @inheritdoc
	 */
	public function getUniqueId()
	{
		// use constant id to allow mapping fake controller names to this one, @see UsrModule::$controllerMap
		return $this->getModule() ? $this->getModule()->getId().'/default' : 'default';
	}

	/**
	 * @inheritdoc
	 */
	public function run($actionID)
	{
		return parent::run(($id=parent::getId()) !== 'default' ? $id : $actionID);
	}

	public function actions()
	{
		$actions = array();
		if ($this->module->captcha !== null) {
			// captcha action renders the CAPTCHA image displayed on the register and recovery page
			$actions['captcha'] = array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
				'testLimit'=>0,
			);
		}
		if ($this->module->dicewareEnabled) {
			// DicewareAction generates a random passphrase
			$actions['password'] = array(
				'class'=>'DicewareAction',
				'length'=>$this->module->dicewareLength,
				'extraDigit'=>$this->module->dicewareExtraDigit,
				'extraChar'=>$this->module->dicewareExtraChar,
			);
		}
		if ($this->module->oneTimePasswordMode != UsrModule::OTP_NONE) {
			// OneTimePasswordAction allows toggling two step auth in user profile
			$actions['toggleOneTimePassword'] = array(
				'class'=>'OneTimePasswordAction',
			);
		}
		return $actions;
	}

	/**
	 * Redirect user depending on whether is he logged in or not.
	 * Performs additional authorization checks.
	 * @param CAction $action the action to be executed.
	 * @return boolean whether the action should continue to be executed.
	 */
	public function beforeAction($action)
	{
		if (!parent::beforeAction($action))
			return false;
		switch($action->id) {
		case 'index':
		case 'profile':
			if (Yii::app()->user->isGuest) {
				$this->redirect(array('login'));
				return false;
			}
			break;
		case 'login':
		case 'recovery':
			if ($action->id === 'recovery' && !$this->module->recoveryEnabled) {
				throw new CHttpException(403,Yii::t('UsrModule.usr', 'Password recovery has not been enabled.'));
			}
			if (!Yii::app()->user->isGuest) {
                $this->redirect(Yii::app()->user->returnUrl !== Yii::app()->request->getRequestUri() ? Yii::app()->user->returnUrl : array(Yii::app()->defaultController));
				return false;
			}
			break;
		case 'register':
			if (!$this->module->registrationEnabled) {
				throw new CHttpException(403,Yii::t('UsrModule.usr', 'Registration has not been enabled.'));
			}
			if (!Yii::app()->user->isGuest) {
				$this->redirect(array('profile'));
				return false;
			}
			break;
		case 'verify':
			if (!isset($_GET['activationKey'])) {
				throw new CHttpException(400,Yii::t('UsrModule.usr', 'Activation key is missing.'));
			}
			break;
		}
		return true;
	}

	/**
	 * Users are redirected to their profile if logged in and to login page otherwise.
	 */
	public function actionIndex()
	{
		$this->redirect(array('profile'));
	}

	/**
	 * Redirects user either to returnUrl or main page.
	 */
	protected function afterLogin()
	{
		$returnUrlParts = explode('/',Yii::app()->user->returnUrl);
		$url = end($returnUrlParts)=='index.php' ? '/' : Yii::app()->user->returnUrl;
		$this->redirect($url);
	}

	/**
	 * Performs user login, expired password reset or one time password verification.
	 * @param string $scenario
	 * @return string
	 */
	public function actionLogin($scenario = null)
	{
		/** @var LoginForm */
		$model = $this->module->createFormModel('LoginForm');
		if ($scenario !== null && in_array($scenario, array('reset', 'verifyOTP'))) {
			$model->scenario = $scenario;
		}

		if (isset($_POST['ajax']) && $_POST['ajax']==='login-form') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		if (isset($_POST['LoginForm'])) {
			$model->setAttributes($_POST['LoginForm']);
			if ($model->validate()) {
				if (($model->scenario !== 'reset' || $model->resetPassword()) && $model->login($this->module->rememberMeDuration)) {
					$this->afterLogin();
				} else {
					Yii::app()->user->setFlash('error', Yii::t('UsrModule.usr', 'Failed to change password or log in using new password.'));
				}
			}
		}
		switch($model->scenario) {
		default: $view = 'login'; break;
		case 'reset': $view = 'reset'; break;
		case 'verifyOTP': $view = 'verifyOTP'; break;
		}
		if(Yii::app()->request->isAjaxRequest)
			$this->renderPartial($view, array('model'=>$model));
		else $this->render($view, array('model'=>$model));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		if (!Yii::app()->user->isGuest)
			Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}

	/**
	 * Processes a request for password recovery email or resetting the password.
	 * @return string
	 */
	public function actionRecovery()
	{
		/** @var RecoveryForm */
		$model = $this->module->createFormModel('RecoveryForm');

		if (isset($_POST['ajax']) && $_POST['ajax']==='recovery-form') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		if (isset($_GET['activationKey'])) {
			$model->scenario = 'reset';
			$model->setAttributes($_GET);
		}
		if (isset($_POST['RecoveryForm'])) {
			$model->setAttributes($_POST['RecoveryForm']);
			/**
			 * If the activation key is missing that means the user is requesting a recovery email.
			 */
			if ($model->activationKey !== null)
				$model->scenario = 'reset';
			if ($model->validate()) {
				if ($model->scenario !== 'reset') {
					/**
					 * Send email appropriate to the activation status. If verification is required, that must happen
					 * before password recovery. Also allows re-sending of verification emails.
					 */
					if ($this->sendEmail($model, $model->identity->isActive() ? 'recovery' : 'verify')) {
						Yii::app()->user->setFlash('success', Yii::t('UsrModule.usr', 'An email containing further instructions has been sent to the email address associated with the specified user account.'));
					} else {
						Yii::app()->user->setFlash('error', Yii::t('UsrModule.usr', 'Failed to send an email.').' '.Yii::t('UsrModule.usr', 'Try again or contact the site administrator.'));
					}
				} else {
					// a valid recovery form means the user confirmed his email address
					$model->getIdentity()->verifyEmail($this->module->requireVerifiedEmail);
					// regenerate the activation key to prevent reply attack
					$model->getIdentity()->getActivationKey();
					if ($model->resetPassword() && $model->login()) {
						$this->afterLogin();
					} else {
						Yii::app()->user->setFlash('error', Yii::t('UsrModule.usr', 'Failed to change password or log in using new password.'));
					}
				}
				$this->redirect(array('recovery'));
			}
		}
		$this->render('recovery',array('model'=>$model));
	}

	/**
	 *
	 */
	public function actionReactivate()
	{
		if(isset($_GET['usr'])){
			$send = $this->module->sendNewActivationEmail($_GET['usr']);
			$this->redirect('login');
		}
	}

	/**
	 * Processes email verification.
	 * @return string
	 */
	public function actionVerify()
	{
		/** @var RecoveryForm */
		$model = $this->module->createFormModel('RecoveryForm', 'verify');
		$model->setAttributes($_GET);
		if ($model->validate() && $model->getIdentity()->verifyEmail($this->module->requireVerifiedEmail)) {
			// regenerate the activation key to prevent reply attack
			$model->getIdentity()->getActivationKey();
			Yii::app()->user->setFlash('success', Yii::t('UsrModule.usr', 'Your email address has been successfully verified.'));
		} else {
			Yii::app()->user->setFlash('error', Yii::t('UsrModule.usr', 'Failed to verify your email address.'));
		}
		$this->redirect(array(Yii::app()->user->isGuest ? 'login' : 'profile'));
	}

	/**
	 * Performs user sign-up.
	 * @return string
	 */
	public function actionRegister()
	{
		/** @var ProfileForm */
		$model = $this->module->createFormModel('ProfileForm', 'register');
		/** @var PasswordForm */
		$passwordForm = $this->module->createFormModel('PasswordForm', 'register');

		if (isset($_POST['ajax']) && $_POST['ajax']==='profile-form') {
			echo CActiveForm::validate(array($model, $passwordForm));
			Yii::app()->end();
		}
		if (isset($_POST['ProfileForm'])) {
			$model->setAttributes($_POST['ProfileForm']);
			if ($model->getIdentity() instanceof IPictureIdentity && !empty($model->pictureUploadRules)) {
				$model->picture = CUploadedFile::getInstance($model, 'picture');
			}
			if (isset($_POST['PasswordForm']))
				$passwordForm->setAttributes($_POST['PasswordForm']);
			if ($model->validate() && $passwordForm->validate()) {
				$trx = Yii::app()->db->beginTransaction();
				if (!$model->save($this->module->requireVerifiedEmail) || !$passwordForm->resetPassword($model->getIdentity())) {
					$trx->rollback();
					Yii::app()->user->setFlash('error', Yii::t('UsrModule.usr', 'Failed to register a new user.').' '.Yii::t('UsrModule.usr', 'Try again or contact the site administrator.'));
				} else {
					$trx->commit();
					if ($this->module->requireVerifiedEmail) {
						if ($this->sendEmail($model, 'verify')) {
							Yii::app()->user->setFlash('success', Yii::t('UsrModule.usr', 'An email containing further instructions has been sent to the provided email address.'));
						} else {
							Yii::app()->user->setFlash('error', Yii::t('UsrModule.usr', 'Failed to send an email.').' '.Yii::t('UsrModule.usr', 'Try again or contact the site administrator.'));
						}
					}
					if ($model->getIdentity()->isActive()) {
						if ($model->login()) {
							$this->afterLogin();
						} else {

protected/modules/usr/views/default/_captcha.php
	<div class="control-group">
		<?php echo $form->labelEx($model,'verifyCode'); ?>
		<div>
		<?php $this->widget('CCaptcha', $this->module->captcha === true ? array() : $this->module->captcha); ?><br/>
		<?php echo $form->textField($model,'verifyCode'); ?>
		</div>
		<div class="hint">
			<?php echo Yii::t('UsrModule.usr', 'Please enter the letters as they are shown in the image above.'); ?><br/>
			<?php echo Yii::t('UsrModule.usr', 'Letters are not case-sensitive.'); ?>
		</div>
		<?php echo $form->error($model,'verifyCode'); ?>
	</div>

protected/modules/usr/views/default/_form.php
<?php /*
@var $this CController
@var $model ProfileForm
@var $passwordForm PasswordForm
 */
?>

	<div class="form-group">
		<?php echo $form->labelEx($model,'username'); ?>
		<?php echo $form->textField($model,'username'); ?>
		<?php echo $form->error($model,'username'); ?>
	</div>

	<div class="form-group">
		<?php echo $form->labelEx($model,'email'); ?>
		<?php echo $form->textField($model,'email'); ?>
		<?php echo $form->error($model,'email'); ?>
	</div>

	<div class="form-group">
		<?php echo $form->labelEx($model,'phone'); ?>
		<?php echo $form->textField($model,'phone'); ?>
		<?php echo $form->error($model,'phone'); ?>
	</div>

<?php if ($model->scenario !== 'register'): ?>
	<div class="form-group">
		<?php echo $form->labelEx($model,'password'); ?>
		<?php echo $form->passwordField($model,'password', array('autocomplete'=>'off')); ?>
		<?php echo $form->error($model,'password'); ?>
	</div>
<?php endif; ?>

<?php if (isset($passwordForm) && $passwordForm !== null): ?>
<?php $this->renderPartial('/default/_newpassword', array('form'=>$form, 'model'=>$passwordForm)); ?>
<?php endif; ?>

	<div class="form-group">
		<?php echo $form->labelEx($model,'firstName'); ?>
		<?php echo $form->textField($model,'firstName'); ?>
		<?php echo $form->error($model,'firstName'); ?>
	</div>

	<div class="form-group">
		<?php echo $form->labelEx($model,'lastName'); ?>
		<?php echo $form->textField($model,'lastName'); ?>
		<?php echo $form->error($model,'lastName'); ?>
	</div>

<?php if ($model->getIdentity() instanceof IPictureIdentity && !empty($model->pictureUploadRules)):
	$picture = $model->getIdentity()->getPictureUrl(80,80);
	if ($picture !== null) {
		$url = $picture['url'];
		unset($picture['url']);
	}
?>
	<div class="form-group">
		<?php echo $form->labelEx($model,'picture'); ?>
		<?php echo $picture === null ? '' : CHtml::image($url, Yii::t('UsrModule.usr', 'Profile picture'), $picture); ?><br/>
		<?php echo $form->fileField($model,'picture'); ?>
		<?php echo $form->error($model,'picture'); ?>
	</div>
	<div class="form-group">
		<?php echo $form->label($model,'removePicture', array('label'=>$form->checkBox($model,'removePicture').$model->getAttributeLabel('removePicture'), 'class'=>'checkbox')); ?>
		<?php echo $form->error($model,'removePicture'); ?>
	</div>
<?php endif; ?>

protected/modules/usr/views/default/_login_remote.php
<?php /*
@var $this DefaultController
@var $model ProfileForm */
$popupScript = <<<JavaScript
function PopupCenter(url, title, w, h) {
    // credits: http://www.xtf.dk/2011/08/center-new-popup-window-even-on.html
    // Fixes dual-screen position                         Most browsers      Firefox
    var dualScreenLeft = window.screenLeft != undefined ? window.screenLeft : screen.left;
    var dualScreenTop = window.screenTop != undefined ? window.screenTop : screen.top;

    width = window.innerWidth ? window.innerWidth : document.documentElement.clientWidth ? document.documentElement.clientWidth : screen.width;
    height = window.innerHeight ? window.innerHeight : document.documentElement.clientHeight ? document.documentElement.clientHeight : screen.height;

    var left = ((width / 2) - (w / 2)) + dualScreenLeft;
    var top = ((height / 2) - (h / 2)) + dualScreenTop;
    var options = 'toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no';
    var newWindow = window.open(url, title, options+', width=' + w + ', height=' + h + ', top=' + top + ', left=' + left);

    if (window.focus) {
        newWindow.focus();
    }
    return false;
}
JavaScript;
Yii::app()->clientScript->registerCssFile(Yii::app()->getAssetManager()->publish(Yii::getPathOfAlias($this->module->id.'.components.assets.zocial')).'/zocial.css');
Yii::app()->clientScript->registerScript(__CLASS__.'#popup', $popupScript, CClientScript::POS_END);
?>
        <ul>
<?php foreach ($this->module->hybridauthProviders as $provider => $settings): if(!$settings['enabled']) continue; ?>
            <li>
                <?php if (Yii::app()->user->isGuest): ?>
                <a class="zocial <?php echo strtolower($provider); ?>" href="<?php echo $this->createUrl('hybridauth/popup', array('provider'=>$provider)); ?>"
                    onclick="return PopupCenter($(this).attr('href'), 'Hybridauth', 400, 550);">
                    <?php echo Yii::t('UsrModule.usr', 'Log in using {provider}', array('{provider}'=>$provider)); ?>
                </a>
                <?php elseif (isset($model) && $model->getIdentity()->hasRemoteIdentity(strtolower($provider))): ?>
                <a class="zocial <?php echo strtolower($provider); ?>" href="<?php echo $this->createUrl('hybridauth/logout', array('provider'=>$provider)); ?>">
                    <?php echo Yii::t('UsrModule.usr', 'Disconnect with {provider}', array('{provider}'=>$provider)); ?>
                </a>
                <?php else: ?>
                <a class="zocial <?php echo strtolower($provider); ?>" href="<?php echo $this->createUrl('hybridauth/popup', array('provider'=>$provider)); ?>"
                    onclick="return PopupCenter($(this).attr('href'), 'Hybridauth', 400, 550);">
                    <?php echo Yii::t('UsrModule.usr', 'Associate this profile with {provider}', array('{provider}'=>$provider)); ?>
                </a>
                <?php endif; ?>
            </li>
<?php endforeach; ?>
        </ul>

protected/modules/usr/views/default/_newpassword.php
	<div class="form-group">
		<?php echo $form->labelEx($model,'newPassword'); ?>
		<?php echo $form->passwordField($model,'newPassword', array('autocomplete'=>'off')); ?>
		<?php echo $form->error($model,'newPassword'); ?>
<?php if ($this->module->dicewareEnabled): ?>
		<span><a id="Users_generatePassword" href="#"><?php echo Yii::t('UsrModule.usr', 'Generate a password'); ?></a></span>
<?php
$diceUrl = $this->createUrl('password');
$diceLabel = Yii::t('UsrModule.usr', 'Use this password?\nTo copy it to the clipboard press Ctrl+C.');
$passwordId = CHtml::activeId($model, 'newPassword');
$verifyId = CHtml::activeId($model, 'newVerify');
$script = <<<JavaScript
$('#Users_generatePassword').on('click',function(){
	$.getJSON('{$diceUrl}', function(data){
		var text = window.prompt("{$diceLabel}", data);
		if (text != null) {
			$('#{$passwordId}').val(text);
			$('#{$verifyId}').val(text);
        }
	});
	return false;
});
JavaScript;
Yii::app()->getClientScript()->registerScript(__CLASS__.'#diceware', $script);
?>
<?php endif; ?>
	</div>

	<div class="form-group">
		<?php echo $form->labelEx($model,'newVerify'); ?>
		<?php echo $form->passwordField($model,'newVerify', array('autocomplete'=>'off')); ?>
		<?php echo $form->error($model,'newVerify'); ?>
	</div>

protected/modules/usr/views/default/generateOTPSecret.php
<?php /*
@var $this DefaultController
@var $model OneTimePasswordForm
@var $url string */

$title = Yii::t('UsrModule.usr', 'One Time Password Secret');
if (isset($this->breadcrumbs))
	$this->breadcrumbs=array($this->module->id, $title);
$this->pageTitle = Yii::app()->name.' - '.$title;
?>
<h1><?php echo $title; ?></h1>

<?php $this->widget('usr.components.UsrAlerts', array('cssClassPrefix'=>$this->module->alertCssClassPrefix)); ?>

<div class="<?php echo $this->module->formCssClass; ?>">
<?php $form=$this->beginWidget($this->module->formClass, array(
	'id'=>'secret-form',
	'enableClientValidation'=>false,
	'clientOptions'=>array(
		'validateOnSubmit'=>false,
	),
	'focus'=>array($model,'code'),
)); ?>

	<?php echo $form->errorSummary($model); ?>

	<p>
<?php if ($this->module->oneTimePasswordMode === UsrModule::OTP_TIME): ?>
		<?php echo Yii::t('UsrModule.usr', 'Scan this QR code using the Google Authenticator application in your mobile phone.'); ?><br/>
		<?php echo CHtml::image($url, Yii::t('UsrModule.usr', 'One Time Password Secret')); ?><br/>
		<?php echo Yii::t('UsrModule.usr', 'Use the Google Authenticator application to generate a one time password and enter it below.'); ?><br/>
<?php elseif ($this->module->oneTimePasswordMode === UsrModule::OTP_COUNTER): ?>
		<?php echo Yii::t('UsrModule.usr', 'A one time password has been sent to your email. Enter it below.'); ?><br/>
<?php endif; ?>
	</p>

	<div class="form-group">
		<?php echo $form->labelEx($model,'oneTimePassword'); ?>
		<?php echo $form->textField($model,'oneTimePassword'); ?>
		<?php echo $form->error($model,'oneTimePassword'); ?>
	</div>

	<div class="buttons">
		<?php echo CHtml::submitButton(Yii::t('UsrModule.usr', 'Submit'), array('class'=>$this->module->submitButtonCssClass)); ?>
	</div>

<?php $this->endWidget(); ?>
</div><!-- form -->

protected/modules/usr/views/default/index.php
<?php
/* @var $this DefaultController */

if (isset($this->breadcrumbs))
	$this->breadcrumbs=array($this->module->id);
?>
<h1><?php echo $this->uniqueId . '/' . $this->action->id; ?></h1>

<?php $this->widget('usr.components.UsrAlerts', array('cssClassPrefix'=>$this->module->alertCssClassPrefix)); ?>

protected/modules/usr/views/default/login.php
<?php /*
@var $this DefaultController
@var $model LoginForm */

$title = Yii::t('UsrModule.usr', 'Log in');
if (isset($this->breadcrumbs))
	$this->breadcrumbs=array($this->module->id, $title);
$this->pageTitle = Yii::app()->name.' - '.$title;
?>
<h1><?php echo $title; ?></h1>

<?php $this->widget('usr.components.UsrAlerts', array('cssClassPrefix'=>$this->module->alertCssClassPrefix)); ?>

<div class="<?php echo $this->module->formCssClass; ?>">
<?php $form=$this->beginWidget($this->module->formClass, array(
	'id'=>'login-form',
	'enableClientValidation'=>true,
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
	'focus'=>array($model,'username'),
)); ?>

	<p class="note"><?php echo Yii::t('UsrModule.usr', 'Fields marked with <span class="required">*</span> are required.'); ?></p>

	<?php echo $form->errorSummary($model); ?>

	<div class="form-group">
		<?php echo $form->labelEx($model,'username'); ?>
		<?php echo $form->textField($model,'username'); ?>
		<?php echo $form->error($model,'username'); ?>
	</div>

	<div class="form-group">
		<?php echo $form->labelEx($model,'password'); ?>
		<?php echo $form->passwordField($model,'password'); ?>
		<?php echo $form->error($model,'password'); ?>
	</div>

<?php if ($this->module->rememberMeDuration > 0): ?>
	<div class="rememberMe form-group">
		<?php echo $form->label($model,'rememberMe', array('label'=>$form->checkBox($model,'rememberMe').$model->getAttributeLabel('rememberMe'), 'class'=>'checkbox')); ?>
		<?php echo $form->error($model,'rememberMe'); ?>
	</div>
<?php endif; ?>

	<div class="form-group buttons">
		<?php echo CHtml::submitButton(Yii::t('UsrModule.usr', 'Log in'), array('class'=>$this->module->submitButtonCssClass)); ?>
	</div>
<?php if ($this->module->recoveryEnabled): ?>
	<p>
		<?php echo Yii::t('UsrModule.usr', 'Don\'t remember username or password?'); ?>
		<?php echo Yii::t('UsrModule.usr', 'Go to {link}.', array(
			'{link}'=>CHtml::link(Yii::t('UsrModule.usr', 'password recovery'), array('recovery')),
		)); ?>
	</p>
<?php endif; ?>
<?php if ($this->module->registrationEnabled): ?>
	<p>
		<?php echo Yii::t('UsrModule.usr', 'Don\'t have an account yet?'); ?>
		<?php echo Yii::t('UsrModule.usr', 'Go to {link}.', array(
			'{link}'=>CHtml::link(Yii::t('UsrModule.usr', 'registration'), array('register')),
		)); ?>
	</p>
<?php endif; ?>
<?php if ($this->module->hybridauthEnabled()): ?>
    <p>
        <?php //echo CHtml::link(Yii::t('UsrModule.usr', 'Sign in using one of your social sites account.'), array('hybridauth/login')); ?>
        <?php $this->renderPartial('_login_remote'); ?>
    </p>
<?php endif; ?>

<?php $this->endWidget(); ?>
</div><!-- form -->

protected/modules/usr/views/default/recovery.php
<?php /*
@var $this DefaultController
@var $model RecoveryForm */

$title = Yii::t('UsrModule.usr', 'Username or password recovery');
if (isset($this->breadcrumbs))
	$this->breadcrumbs=array($this->module->id, $title);
$this->pageTitle = Yii::app()->name.' - '.$title;
?>
<h1><?php echo $title; ?></h1>

<?php $this->widget('usr.components.UsrAlerts', array('cssClassPrefix'=>$this->module->alertCssClassPrefix)); ?>

<div class="<?php echo $this->module->formCssClass; ?>">
<?php $form=$this->beginWidget($this->module->formClass, array(
	'id'=>'recovery-form',
	'enableClientValidation'=>true,
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
	'focus'=>array($model,$model->scenario==='reset' ? 'newPassword' : 'username'),
)); ?>

	<p class="note"><?php echo Yii::t('UsrModule.usr', 'Fields marked with <span class="required">*</span> are required.'); ?></p>

	<?php echo $form->errorSummary($model); ?>

<?php if ($model->scenario === 'reset'): ?>
	<?php echo $form->hiddenField($model,'username'); ?>
	<?php echo $form->hiddenField($model,'email'); ?>
	<?php echo $form->hiddenField($model,'activationKey'); ?>

<?php $this->renderPartial('_newpassword', array('form'=>$form, 'model'=>$model)); ?>
<?php else: ?>
	<div class="form-group">
		<?php echo $form->labelEx($model,'username'); ?>
		<?php echo $form->textField($model,'username'); ?>
		<?php echo $form->error($model,'username'); ?>
	</div>

	<div class="form-group">
		<?php echo $form->labelEx($model,'email'); ?>
		<?php echo $form->textField($model,'email'); ?>
		<?php echo $form->error($model,'email'); ?>
	</div>

<?php if($model->asa('captcha') !== null): ?>
<?php $this->renderPartial('_captcha', array('form'=>$form, 'model'=>$model)); ?>
<?php endif; ?>
<?php endif; ?>

	<div class="form-group buttons">
		<?php echo CHtml::submitButton(Yii::t('UsrModule.usr', 'Submit'), array('class'=>$this->module->submitButtonCssClass)); ?>
	</div>

<?php $this->endWidget(); ?>
</div><!-- form -->